import './globals.css'
import AuthProvider from '@/components/AuthProvider';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: "Nextjs blog",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative bg-gradient-to-r from-red-950 via-yellow-700 to-red-950">
        <div className="fixed w-full h-full bg-[url('../public/images/homebg.png')] bg-center bg-cover bg-no-repeat -z-10" />
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
