export const images = [
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 1",
    info: "Fannius Scholtenstraat 1983",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat2.jpg",
    alt: "Image 2",
    info: "Van Limburg Stirumplein 1952",
    jaar: 1952,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 3",
    info: "Info about Image 3",
    jaar: 1990,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 4",
    info: "Info about Image 4",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 5",
    info: "Info about Image 5",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 6",
    info: "Info about Image 6",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 1",
    info: "Info about Image 7",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 2",
    info: "Info about Image 8",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat2.jpg",
    alt: "Image 3",
    info: "Info about Image 9",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 4",
    info: "Info about Image 10",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 5",
    info: "Info about Image 11",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 6",
    info: "Info about Image 12",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 1",
    info: "Kaart tramlijn 19",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 2",
    info: "Info about Image 14",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 3",
    info: "Info about Image 15",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 4",
    info: "Info about Image 16",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 5",
    info: "Info about Image 17",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 6",
    info: "Info about Image 18",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 1",
    info: "Info about Image 19",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 2",
    info: "Info about Image 20",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 3",
    info: "Info about Image 21",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 4",
    info: "Info about Image 22",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/lijn19.png",
    alt: "Image 5",
    info: "Info about Image 23",
    jaar: 1983,
  },
  {
    src: "/images/toenennu/straat.jpg",
    alt: "Image 6",
    info: "Info about Image 24",
    jaar: 1983,
  },
];
