export const images = [
  {
    src: "/images/toenennu/fanniusscholtenstraat_4.jpg",
    alt: "fanniusscholtenstraat",
    info: "Fannius Scholtenstraat 1983",
    jaar: 1983,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1983",
  },
  {
    src: "/images/toenennu/vanlimburgstirumplein.jpg",
    alt: "vanlimburgstirumplein",
    info: "Van Limburg Stirumplein 1952",
    jaar: 1952,
    title: "Van Limburg Stirumplein",
    description: "Van Limburg Stirumplein 1952",
  },
  {
    src: "/images/toenennu/vanboetzelaerstraat_1.jpg",
    alt: "Image 3",
    info: "Van Boetzelaerstraat 1964",
    jaar: 1964,
    title: "Van Boetzelaerstraat",
    description: "Van Boetzelaerstraat 1964",
  },
  {
    src: "/images/toenennu/vanboetzelaerstraat_2.jpg",
    alt: "Image 3",
    info: "Van Boetzelaerstraat 1983",
    jaar: 1983,
    title: "Van Boetzelaerstraat",
    description: "Van Boetzelaerstraat 1983",
  },
  {
    src: "/images/toenennu/fanniusscholtenstraat_1.jpg",
    alt: "Image 4",
    info: "Fannius Scholtenstraat 1915",
    jaar: 1915,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1915",
  },
  {
    src: "/images/toenennu/fanniusscholtenstraat_2.jpg",
    alt: "Image 4",
    info: "Fannius Scholtenstraat 1915",
    jaar: 1915,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1915",
  },
  {
    src: "/images/toenennu/fanniusscholtenstraat_3.jpg",
    alt: "Image 4",
    info: "Fannius Scholtenstraat 1915",
    jaar: 1915,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1915",
  },
];
