export const images = [
  {
    src: "/images/toenennu/fanniusscholtenstraat_4.jpg",
    alt: "fanniusscholtenstraat",
    info: "Fannius Scholtenstraat 1983",
    jaar: 1983,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1983",
  },
  {
    src: "/images/toenennu/vanlimburgstirumplein.jpg",
    alt: "vanlimburgstirumplein",
    info: "Van Limburg Stirumplein 1952",
    jaar: 1952,
    title: "Van Limburg Stirumplein",
    description: "Van Limburg Stirumplein 1952",
  },
  {
    src: "/images/toenennu/vanboetzelaerstraat_1.jpg",
    alt: "Image 3",
    info: "Van Boetzelaerstraat 1964",
    jaar: 1964,
    title: "Van Boetzelaerstraat",
    description: "Van Boetzelaerstraat 1964",
  },
  {
    src: "/images/toenennu/vanboetzelaerstraat_2.jpg",
    alt: "Image 3",
    info: "Van Boetzelaerstraat 1983",
    jaar: 1983,
    title: "Van Boetzelaerstraat",
    description: "Van Boetzelaerstraat 1983",
  },
  {
    src: "/images/toenennu/fanniusscholtenstraat_1.jpg",
    alt: "Image 4",
    info: "Fannius Scholtenstraat 1915",
    jaar: 1915,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1915",
  },
  {
    src: "/images/toenennu/fanniusscholtenstraat_2.jpg",
    alt: "Image 4",
    info: "Fannius Scholtenstraat 1915",
    jaar: 1915,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1915",
  },
  {
    src: "/images/toenennu/fanniusscholtenstraat_3.jpg",
    alt: "Image 4",
    info: "Fannius Scholtenstraat 1915",
    jaar: 1915,
    title: "Fannius Scholtenstraat",
    description: "Fannius Scholtenstraat 1915",
  },
  {
    src: "/images/toenennu/vanbeuningenplein_1.jpg",
    alt: "Image 4",
    info: "Van Beuningenplein 1946",
    jaar: 1946,
    title: "Van Beuningenplein",
    description: "Van Beuningenplein 1946",
  },
  {
    src: "/images/toenennu/vanbeuningenplein_2.jpg",
    alt: "Image 4",
    info: "Van Beuningenplein 1989",
    jaar: 1989,
    title: "Van Beuningenplein",
    description: "Van Beuningenplein 1989",
  },
  {
    src: "/images/toenennu/vanbeuningenstraat_1.jpg",
    alt: "Image 4",
    info: "Van Beuningenstraat 1935",
    jaar: 1935,
    title: "Van Beuningenstraat",
    description: "Van Beuningenstraat 1935",
  },
  {
    src: "/images/toenennu/dekempenaerstraat_1.jpg",
    alt: "Image 4",
    info: "De Kempenaerstraat 1975",
    jaar: 1975,
    title: "De Kempenaerstraat",
    description: "De Kempenaerstraat 1975",
  },
  {
    src: "/images/toenennu/bentinckstraat_1.jpg",
    alt: "Image 4",
    info: "Bentinckstraat 1922",
    jaar: 1922,
    title: "Bentinckstraat",
    description: "Bentinckstraat 1922",
  },
  {
    src: "/images/toenennu/dewittenstraat_1.jpg",
    alt: "Image 4",
    info: "De Wittenstraat 1931",
    jaar: 1931,
    title: "De Wittenstraat",
    description: "De Wittenstraat 1931",
  },
  {
    src: "/images/toenennu/dewittenstraat_2.jpg",
    alt: "Image 4",
    info: "De Wittenstraat 1983",
    jaar: 1931,
    title: "De Wittenstraat",
    description: "De Wittenstraat 1983",
  },
  {
    src: "/images/toenennu/haarlemmerweg_1.jpg",
    alt: "Image 4",
    info: "Haarlemmerweg 1948",
    jaar: 1931,
    title: "Haarlemmerweg",
    description: "Haarlemmerweg 1948",
  },
];
